services:
  - type: web
    name: ideasync
    env: docker
    plan: free
    envVars:
      - key: PORT
        value: 8080
      - key: DB_HOST
        fromDatabase:
          name: ideasync-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: ideasync-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: ideasync-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: ideasync-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: ideasync-db
          property: password

databases:
  - name: ideasync-db
    plan: free
    databaseName: ideasync
    user: ideasync_user
